<?php
/******************************** Defintions *******************************
  session:used to store informations temporary in the "Server" and you can use 
  anywhere as long as the time not expired
  and play a crucial role in web  for maintaining stateful information 
  across multiple pages or interactions with a website for a specific user.
  ---------------------------------------------------------------------------
  ob_start():is a function used to turn on output buffering.
            Output buffering is a mechanism that allows you to capture the 
            output generated by PHP scripts before sending it to the browser
  ---------------------------------------------------------------------------  
  session_start() :- is a function used to start a new or resume an existing 
                     session and Any data stored in the $_SESSION superglobal array will be available for the current session. 
                     This data can be set, retrieved, and manipulated across different pages during the session   
  ---------------------------------------------------------------------------
   ob_end_flush() :- is a function used to flush (send) the contents of the 
                     output buffer and turn off output buffering. 
 ---------------------------------------------------------------------------
 Cookies : used to store information about a user's interactions with a website 
 and can be  manipulated by both the server-side PHP scripts and client-side scripts such as JavaScript.   
 ----------------------------------------------------------------------------
 Regular Expressions:- they are used to faciliate finding a number or substring in a string                                   

*/
/********************************** SESSIONS ******************************** 
ob_start(); 

session_start([
  'cookie_lifetime'=>1,   //the life time of this session that is valid
]);

//then you have to set the session

//$_SESSION['key'] = 'test value';

//destory all the sessions in the server
session_destroy();
echo $_SESSION['key'];

ob_end_flush(); 
****************************************************************************/
/******************************** COOKIES*********************************************
ob_start();
setcookie('cookie','test_cookie',time()+100);//setting cookie
ob_end_flush();
*************************************************************************************/

#Regular Expressions
/*
$string = "<a href=\"google.com\">Click My</a>";
$paterrn = '/<a href="(.*?)">/';
preg_match($paterrn,$string,$matches);
var_dump($matches[1]);
*/

#FileSystems 
/*
if(!is_dir("storage")){
  mkdir("storage",0x0777);//create direcory with full permission
}

$file = fopen('file.txt','w'); //create a file with write permission
fwrite($file,"Mohamed Ali Klay\n"); //write in this file
fwrite($file,"Mohamed Ali Klay\n"); //same
fclose($file);           //close this file from ram to manage resources
$file = fopen('file.txt','r'); //open this file again to read the content
while(!feof($file)){
  echo fgets($file)."<br>";   //gets the content line by line
}
fclose($file);   //close this file from ram to manage resources
*/
/*
$file = file_get_contents("file.txt");//to get the content of a file

file_put_contents("file.txt",$file."\n\r again"); //to append contents into this file

*/
#time and data in php
/*
$time = time();  //get the time in time unix
date_default_timezone_set('Africa/Cairo');//set the time zone
//echo date_default_timezone_get();
$date = date('d-m-Y h:i:s',$time); //convert the time from time unix into date
$new_date = strtotime($date); //to convert the date in time unix format
$final_time = strtotime("+1 month",$new_date); //you can modify the date only with the time unix
echo date('d-m-Y h:i:s',$final_time);//convertd again into date 
*/
/*
$tr = timezone_identifiers_list();
foreach($tr as $ts){
  echo $ts."<br>";
}
*/
/*********************************************************************************************
                                          DataBase MySQL
/********************************************************************************************/
/*
$database_info = include __DIR__."/config/database_info.php";//include databse_info
/*connecting with the database using mysqli extention
$connect = mysqli_connect($database_info['servername'],
    $database_info['username'],
    $database_info['password'],
    $database_info['database'],
    $database_info['port']);

if(!$connect){
  die("conection faild".mysqli_connect_error());
}
//to create database called php
//mysqli_query($connect,"CREATE DATABASE PHP");

//the SQL query instructions
$sql = "INSERT INTO users (name,email,password) VALUES 
('Mohamed Ali_1 Klay','klay1@php.net','12345');";
$sql .= "INSERT INTO users (name,email,password) VALUES 
('Mohamed Ali_2 Klay','klay1@php.net','12345');";
$sql .= "INSERT INTO users (name,email,password) VALUES 
('Mohamed Ali_3 Klay','klay1@php.net','12345');";
//insert the query into the database
//$query = mysqli_query($connect,$sql);

//insert mulitiple queries at the same time
$query = mysqli_multi_query($connect,$sql);
//get ID of the last inserted record
$last = mysqli_insert_id($connect);
echo "The last inserted id ->".$last;
mysqli_close($connect);  //close the connection with the database
*/

/*
$data=db_insert('users',[
  'name'=>'mohamed8_sayed',
  'email'=>'mohamed9@php.net',
  'password'=>'1234556'
]);
var_dump($data);
*/
/*
$data=db_update('users',[
  'name'=>'klay_sayed',
  'email'=>'klay@php.net',
  'password'=>'987654'
],1);
var_dump($data);
*/
//db_delete('users',1);
//var_dump(db_find('users',2));
//var_dump(db_search('users',"where email='klay1@php.net'"));
/*
$users=db_get('users',"where name like '%klay%'");
if($users['num']>0){
    while($row = mysqli_fetch_assoc($users['query'])){
        echo $row['name']."<br>";
    }
}
*/
/*
$users=db_paginate('users',"",1);
while($row=mysqli_fetch_assoc($users['query'])){
    echo $row['email']."<br>";
}

echo $users['render'];
*/

require_once __DIR__."/../includes/app.php";

//set session
//session('test','this my test value');
//delete all session
//session_delete_all();
//get the session
//echo session('test');

//var_dump(config('session.timeout'));
// $encrypted= encrypt('this is my Freind mohamed ali klay');
// echo decrypt($encrypted);
//session('locale');

// $link_path = base_path('storage/files/images');
// $final_link = str_replace('\\'.'public'.'/..','',$link_path);
// echo $final_link;
//symlink('../storage/files/categories', '../public/storage');
//var_dump(segment());


/*****File managment on storage Folder */
//delete_file('../storage/files/images/img.png'); //delet files
//storage('../storage/files/images/img.png');   //show or download file
//remve_folder('../temp');  //to remove folders
route_init();

if(config('database_info.strict')){
  db_setting_strict();
}
/**to send a mail */
// var_dump(send_mail(['php@mail.com','php@mail.com'], ['this fake mail','this fake mail'], ['hi klay','hi klay']));

if(!empty($GLOBALS['query'])){
  //var_dump($GLOBALS['query']);
  mysqli_free_result($GLOBALS['query']);//to free memory
}
ob_end_flush();
mysqli_close($connect);  //close the connection with the database